naming_rules:
  title_year_format:
    regex: (?<title>.+?)\.(?<year>19[0-9]{2}|20[0-2][0-9]|2030)\..*
    supported_media_types: 
      - movie
    example: "Inception.2010.1080p.BluRay.x264-Group.mkv"

  title_year_cntitle_subtitle_format:
    regex: (?<title>[\w.]+)\.(?<year>19[0-9]{2}|20[0-2][0-9]|2030)\.(?<nonengtitle>[\u4e00-\u9fa5]+)\.(?<subtitle>[\u4e00-\u9fa5]{2}字幕)\..*
    supported_media_types:
      - movie
      - tv_show
    example: "Assassins.1995.刺客战场.双语字幕.HR-HDTV.AC3.1024x576.x264-人人影视制作.mkv"

  title_year_2_format:
    regex: (?<title>.+) \((?<year>\d{4})\).*
    supported_media_types:
      - movie
      - tv_show
    example: "The Shawshank Redemption (1994).mp4"

  tv_show_season_episode:
    regex: (?<title>.+?)\.S(?<season>\d{2})E(?<episode>\d{2})\..*
    supported_media_types:
      - tv_show
      - anime
    example: "Breaking.Bad.S01E01.720p.BluRay.x264.mkv"

  multilanguage_subtitle_format:
    regex: (?<title>.+?)\.(?<year>\d{4})\..*Subtitles.*
    supported_media_types: 
      - movie
    example: The.Dark.Knight.2008.Eng.Chi.Subtitles.1080p.BluRay.x264-Group.mkv

  version_control_format:
    regex: (?<title>.+?)\.(?<year>\d{4})\.(Directors|Extended)\.Cut\..*
    supported_media_types: 
      - movie
    example: Blade.Runner.1982.Directors.Cut.BluRay.x264.mkv

  non_english_title_format:
    regex: (?<title>.+?)\.(?<nonengtitle>.+?)\.(?<year>\d{4})\..*
    supported_media_types: 
      - movie
    example: Crouching.Tiger.Hidden.Dragon.卧虎藏龙.2000.1080p.BluRay.x264-Group.mkv

  simple_title_with_year:
    regex: (?<title>.+?)(?<year>\d{4})\..*
    supported_media_types: 
      - movie
      - book
    example: Matrix1999.mkv

  title_only:
    regex: (?<title>.+?)\..*
    supported_media_types: 
      - movie
      - music
      - book
    example: Inception.mkv